name: Renovate Config Validator

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - default.json

jobs:
  renovate-config-validator:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install the Renovate CLI
        run: npm install -g renovate
      - name: Validate the Renovate config
        run: RENOVATE_CONFIG_FILE="default.json5" renovate-config-validator
